Add configuration option to allow ignoring missing hooks dir
STAR-ZERO/gradle-githook pull request #2
Opened 2018-11-02 08:28 UTC by grusell

In some situations the githooks dir may be missing due to factors outside our control (ie git clone template on build server not including hooks dir). For cases like this, it seems useful to be able to configure the plugin so that the build does not fail due to missing hooks directory.

2018-11-28 09:30 UTC, grusell commented
@STAR-ZERO Do you think you could have a look at my PR? Would like to use your gradle plugin but am currently unable to do so because of how our build system is set up. Cheers.

2018-11-28 12:00 UTC, STAR-ZERO commented
Sorry, I'm so late. I'll check your PR on the weekend. Please wait a moment. 🙇

2018-11-29 08:18 UTC, grusell commented
That would be grate, thanks :) .

2018-11-30 14:07 UTC, STAR-ZERO requested changes

2018-11-30 14:07 UTC, STAR-ZERO commented on githook/src/main/kotlin/com/star_zero/gradle/githook/GithookPlugin.kt
> +            else log.info("Can't find hooks directory ${extension.hooksDir}, no hooks written")
Please use `{` and `}` for `if` statement. 🙏 I think it's readable.

2018-12-03 06:22 UTC, grusell commented on githook/src/main/kotlin/com/star_zero/gradle/githook/GithookPlugin.kt
> +            else log.info("Can't find hooks directory ${extension.hooksDir}, no hooks written")
Fixed it.

2018-12-04 13:18 UTC, STAR-ZERO approved these changes

2018-12-04 13:19 UTC, STAR-ZERO commented
Thanks 👍

2018-12-04 13:19 UTC, merged